# Generated by Django 3.0.7 on 2020-06-22 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogman', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogtext',
            old_name='blog',
            new_name='blog_id',
        ),
    ]
