# Generated by Django 3.0.7 on 2020-06-22 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogman', '0003_auto_20200622_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentText', models.TextField()),
                ('blog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogman.Blog')),
            ],
        ),
    ]
