# Generated by Django 3.0.7 on 2020-06-23 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogman', '0005_auto_20200623_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='visitor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blogman.Visitor'),
        ),
    ]
