# Generated by Django 3.0.7 on 2020-06-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogman', '0006_auto_20200623_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='visitor_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='visitor_name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commentText',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.DeleteModel(
            name='Visitor',
        ),
    ]
